### ISSUE TITLE
LICENSEファイルでライセンスを明示すると良いのでは？

### ISSUE THREAD

**Issue by cosmo0920** [roamer7038/KanColleBrowser#1]
GitHubに置いた時点でGitHubのライセンス条項に従うことになります。
が、これだとプルリクエストとかの時にどのようにコードを取り扱うかの決まりがない状態なので問題を見つけた時に報告したくてもできないことになってしまいます。
あと、ユーザーにAt your own risk(自己責任)で使ってくださいと明示する意味でもリポジトリに入れておいたほうが良いです。

一時ソースさえ明示すれば良いようなゆるいライセンスから、コードを改変した場合にも公開義務のあるライセンスまで色々とあるので何が良いのか探してみてください。

例えばMITやBSD2条項・3条項ライセンスは比較的ゆるいライセンスです。また、Apache 2.0ライセンスは特許の使用許諾も絡んできます。かなりゆるいライセンスはBoost License 1.0です。これはソースコード上にのみライセンスを表示すればよいライセンスです。
ユーザーの改変の自由を保障するライセンスはGPL系のライセンス(GPL-2, GPL-3, AGPL)がそれに該当します。本当に改変後のコードも開示してほしいのであればこの系列のライセンスを選択するとよいでしょう。

てことで表示するとこんなよいことがありますよ！というIssueです！！

**Comment by cosmo0920** [comment]
@roamer7038 LICENSEファイルを置けているのが確認出来たのでこれを閉じちゃってください！

**Comment by roamer7038** [comment]
アドバイスありがとうございました！
